---
repos:
  # ==================== General =========================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files  # avoid giant file commit accidents
      - id: check-case-conflict  # avoid case sensitivity in file names
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: name-tests-test  # follow pytest naming convention
      - id: requirements-txt-fixer
      - id: check-merge-conflict  # avoid lingering merge markers
      - id: mixed-line-ending  # Use Unix line-endings to avoid big no-op CSV diffs.
        args: [--fix=lf]
  - repo: https://github.com/google/yamlfmt
    rev: v0.10.0
    hooks:
      - id: yamlfmt
        name: YAML Formatter (yamlfmt)
        description: Formats YAML files using Google's yamlfmt with inline configuration
          options.
        language: golang
        types: [yaml]
        args:
          - -formatter=include_document_start=true
          - -formatter=indent=2
          - -formatter=max_line_length=80
          - -formatter=pad_line_comments=2
          - -formatter=trim_trailing_whitespace=true
          - -formatter=eof_newline=true
          - -formatter=gitignore_path=".gitignore"
  - repo: local
    hooks:
      - id: smoked-pc-config-check
        name: Pre-Commit Config Smoke Test
        description: Validate .pre-commit-config.yaml against .ST-pre-commit-config.yaml
          files.
        entry: bin/smoked-pc-config/main.sh
        language: system
        pass_filenames: false  # Prevent passing file paths since the script handles them internally.
        always_run: true  # Ensures the hook runs even if no files have changed.
exclude: ^test/smoke-test/.*$
