---
# Filename: .github/workflows/auto-pr-approval
name: Auto-Approve Pull Requests
on:
  pull_request_target:
    types: [opened, reopened]
    branches:
      - main
permissions: {}
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:  # elevated permissions at the job level
      contents: read  # Needed for fetching repo data (e.g., collaborators)
      pull-requests: write  # Needed to approve pull requests
    steps:
      # Step 1: Fetch Admin Collaborators
      - name: Fetch Admin Collaborators
        id: fetch-admins
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use mock value if present, otherwise fetch from GitHub API
          if [[ -n "${MOCK_ADMIN_COUNT}" ]]; then
            echo "Mocking admin count: \"$MOCK_ADMIN_COUNT\""
            admin_count="$MOCK_ADMIN_COUNT"
          else
            admin_count=$(gh api /repos/${{ github.repository }}/collaborators \
              --jq '.[] | select(.permissions.admin == true)' | wc -l)
          fi
          echo "Number of admins: \"$admin_count\""
          echo "admin_count=\"$admin_count\"" >> "$GITHUB_ENV"
      # Step 2: Conditionally Approve PR
      - name: Auto-Approve PR
        if: env.admin_count == '1'
        uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto approved automated PR"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      # Step 3: Skip Approval if Multiple Admins
      - name: Skip Auto-Approval
        if: env.admin_count != '1'  # Skip if more than one admin exists
        run: echo "Multiple admins detected. Approval requires manual review."
