---
# Filename: .github/workflows/main.yaml
name: Main Workflow Orchestrator
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:
#env:
#  GH_TOKEN: ${{ github.token }}  # Set globally
jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
      - name: Environment Setup
        uses: ./.github/actions/setup-environment
      - name: Restore Pacman Cache
        uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: pacman-cache-${{ runner.os }}-${{ hashFiles('build.yml') }}
          restore-keys: |-
            pacman-cache-${{ runner.os }}-
      - name: Run BATS Tests
        run: bats test/test_common_setup.bats
  protect-branches:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        is_default_branch: ["true", "false"]
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
      - name: Apply Branch Protection
        uses: ./.github/actions/branch-protection
        with:
          is_default_branch: ${{ matrix.is_default_branch }}
          GH_TOKEN: ${{ github.token }}
