---
# Filename: .github/workflows/main.yaml
name: Main Workflow Orchestrator
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:
jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
      - name: Environment Setup
        uses: ./.github/actions/setup-environment
      - name: Restore Pacman Cache
        uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: pacman-cache-${{ runner.os }}-${{ hashFiles('build.yml') }}
          restore-keys: |-
            pacman-cache-${{ runner.os }}-
      - name: Run BATS Tests
        run: bats test/test_common_setup.bats
  protect-default-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Protection for Default Branch
        uses: ./.github/actions/branch-protection
        with:
          is_default_branch: "true"
  protect-non-default-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Protection for Non-Default Branch
        uses: ./.github/actions/branch-protection
        with:
          is_default_branch: "false"
